# site settings

title: Yun-Hsuan CHANG
description: Protfolio site and blog for Yun
taglong: Junior data engineer & full stack developer
tagshort: Yun's site
url: https://tiffanychang-fr.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/tiffanychang-fr/tiffanychang-fr.github.io

# author settings

author:
  name: Yun-Hsuan CHANG
  email: changyunhsuan.fr@gmail.com
photo: /assets/jpg/photo.jpg
postimage: /assets/posts
portfolioimage: /assets/portfolio

# social media links

social:
  github: tiffanychang-fr
  linkedin: yunhsuanchang

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
